# Development Configuration
# Base configuration for development environment

app:
  name: "arc-prize-2025"
  version: "0.1.0"
  debug: true
  environment: "development"

api:
  host: "0.0.0.0"
  port: 8000
  reload: true
  workers: 1
  cors:
    allow_origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
    allow_credentials: true
    allow_methods:
      - "GET"
      - "POST" 
      - "PUT"
      - "DELETE"
      - "OPTIONS"

websocket:
  host: "0.0.0.0"
  port: 8001
  cors_allowed_origins: "*"

database:
  url: "sqlite:///./data/arc_prize.db"
  pool_size: 5
  max_overflow: 10
  echo: true

cache:
  type: "diskcache"
  directory: "./data/cache"
  size_limit: "1GB"
  default_ttl: 3600

logging:
  level: "DEBUG"
  format: "json"
  file: "./logs/arc_prize.log"
  rotation: "daily"
  retention: 7

model:
  name: "llama-3-8b"
  device: "auto"
  quantization: true
  max_length: 2048
  batch_size: 16
  
training:
  epochs: 5
  learning_rate: 1e-4
  batch_size: 4
  gradient_accumulation_steps: 2
  warmup_steps: 100
  
inference:
  batch_size: 8
  max_tokens: 256
  temperature: 0.7
  top_p: 0.9

monitoring:
  metrics_enabled: true
  metrics_port: 9090
  profiling_enabled: false

# Health check configuration (development settings)
health_check:
  enabled: true
  check_interval_seconds: 30
  timeout_seconds: 5
  max_failures: 3
  degraded_threshold_ms: 1000.0
  unhealthy_threshold_ms: 5000.0
  components_to_check:
    - database
    - cache
    - wandb
    - storage
    - memory
    - cpu
  
security:
  rate_limit:
    # Global rate limiting settings
    enabled: true
    use_redis: false
    redis_url: "redis://localhost:6379/0"
    
    # Evaluation endpoints (more restrictive for DoS protection)
    evaluation:
      requests_per_minute: 100
      requests_per_hour: 1000
      burst_size: 10
    
    # Dashboard endpoints (more permissive for UI)
    dashboard:
      requests_per_minute: 1000
      requests_per_hour: 10000
      burst_size: 50
    
    # Authentication endpoints
    auth:
      requests_per_minute: 20
      requests_per_hour: 200
    
    # WebSocket connections per IP
    websocket:
      connections_per_ip: 5
    
    # Advanced protection
    adaptive_limiting: true
    suspicious_threshold_multiplier: 2.0
    whitelist_ips: []
    blacklist_ips: []
    
resources:
  max_memory_gb: 8
  max_concurrent_tasks: 2
  max_processing_time: 300
  
features:
  hot_reload: true
  experiment_tracking: false
  ttt_training: false
  program_synthesis: false