# Production Configuration
# Configuration for production deployment

app:
  name: "arc-prize-2025"
  version: "0.1.0"
  debug: false
  environment: "production"

api:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 4  # Multiple workers for production

websocket:
  host: "0.0.0.0"
  port: 8001
  cors_allowed_origins:
    - "https://yourdomain.com"

database:
  url: "sqlite:///./data/arc_prize.db"
  pool_size: 20
  max_overflow: 40
  echo: false  # Disable SQL logging in production

cache:
  type: "diskcache"
  directory: "./data/cache"
  size_limit: "5GB"
  default_ttl: 7200

logging:
  level: "INFO"
  format: "json"
  file: "./logs/arc_prize.log"
  rotation: "daily"
  retention: 30  # Keep logs for 30 days

model:
  name: "llama-3-8b"
  device: "cuda"
  quantization: true
  max_length: 2048
  batch_size: 32

training:
  epochs: 20
  learning_rate: 5e-5
  batch_size: 16
  gradient_accumulation_steps: 1

inference:
  batch_size: 32
  max_tokens: 512
  temperature: 0.5  # More conservative in production
  top_p: 0.8

monitoring:
  metrics_enabled: true
  metrics_port: 9090
  profiling_enabled: false

security:
  rate_limit:
    # Global rate limiting settings - more restrictive in production
    enabled: true
    use_redis: true  # Use Redis for production clustering
    redis_url: "${REDIS_URL:-redis://localhost:6379/0}"
    
    # Evaluation endpoints (stricter for production DoS protection)
    evaluation:
      requests_per_minute: 50   # More restrictive than development
      requests_per_hour: 500
      burst_size: 5
    
    # Dashboard endpoints (balanced for production UI)
    dashboard:
      requests_per_minute: 500   # Lower than development
      requests_per_hour: 5000
      burst_size: 25
    
    # Authentication endpoints (very restrictive)
    auth:
      requests_per_minute: 10
      requests_per_hour: 100
    
    # WebSocket connections per IP (more restrictive)
    websocket:
      connections_per_ip: 3
    
    # Advanced protection (enabled in production)
    adaptive_limiting: true
    suspicious_threshold_multiplier: 3.0  # More aggressive
    whitelist_ips: []  # Configure via environment
    blacklist_ips: []  # Configure via environment

resources:
  max_memory_gb: 16
  max_concurrent_tasks: 8
  max_processing_time: 600  # Longer timeout for production

features:
  hot_reload: false
  experiment_tracking: true
  ttt_training: true
  program_synthesis: true